### ISSUE TITLE
[NEXT 10th Assignment] Session 0 - Git 버전관리 기초

### ISSUE THREAD

**Issue by deborah91298** [NEXT-LIKELION/2022-NEXT-Assignment#1]
📌 다음 두 가지를 실행해주세요.

### 1) 자신 만의 과제 레포지토리를 만든 다음에 Session0_HW 디렉토리 밑에 본인 만의 README 작성해주세요. (마감: 3/14 세션 전)
- 내용은 자기 소개 등 본인이 적고 싶은 내용으로 작성해주세요.

[도전과제] (선택)
- 헤더 추가 (힌트: ```#``` 하나 추가할 때마다 크기 달라짐)
- 링크 연결 (예시: ```[링크를 나타낼 문구](링크)```)
- 그림 추가 (예시: ```![그림 이름](그림 경로)```) -> 그냥 이미지 drag and drop 하셔도 됩니다!

[댓글 업로드 예시]
> 1. 이름
> 2. 과제 링크

### 2) 코드카데미 강의를 수강해주세요.(*pro 제외) (마감: 3/17 세션 전)
_인증 방법은 월요일 세션 때 공지될 예정입니다. 우선은 강의만 수강해주세요~!_
- Learn HTML
- Learn CSS

**Comment by notaonce** [comment]
1. 한성수
2. https://github.com/notaonce/Assignment1

**Comment by alswlalswl1013** [comment]
1. 김민지
2. https://github.com/alswlalswl1013/LIKELION2022

**Comment by ziweek** [comment]
1. 김지욱
2. https://github.com/ziweek/likelion

**Comment by ghost** [comment]
1. 김지욱
2. https://github.com/ziweek/likelion/tree/master/Assignments/Session0_HW

**Comment by toyo30** [comment]
1. 백민기
2. https://github.com/toyo30/next-like-lion/tree/main/Session0_HW

**Comment by seoulmango** [comment]
1. 박기만
2. https://github.com/seoulmango/Likelion2022_HW

**Comment by eauchan** [comment]
1. 이의찬
2. https://github.com/eauchan/Next_LikeLion

**Comment by Moi1oM** [comment]
1. 전성운
2. https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session0_HW

**Comment by Park747** [comment]
1. 박견우
2. https://github.com/Park747/Park747/tree/main/Session0_Hw

**Comment by sde0116** [comment]
1. 서다은
2. https://github.com/sde0116/NextLikelion.git

**Comment by nymvmt** [comment]
1. 김나영
2. https://github.com/nymvmt/Next_Likelion_2022/tree/master/Session0_HW

**Comment by onelee812** [comment]
1. 이예원
2. https://github.com/onelee812/LikeLion22_HW.git

**Comment by 99rbbt** [comment]
1. 신재현
2. https://github.com/99rbbt/Nextlion2022/tree/master/Session0_HW

**Comment by Canada-Joose** [comment]
1. 주장규
2. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session0_HW

**Comment by sophiahyj** [comment]
1. 한예진
2. https://github.com/sophiahyj/likelionHW/tree/master/Session0_HW

**Comment by ssoy0514** [comment]
1. 이소희
2. https://github.com/ssoy0514/NEXTxLIKELION-Session0/tree/master/Session0_HW

**Comment by CryingDitto** [comment]
1. 이지은
2. https://github.com/CryingDitto/NextLionX/tree/master/Session0_HW

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session0_HW

**Comment by willbeagangsta** [comment]
1. 김하경
2.  https://github.com/willbeagangsta/NEXT_LikeLion_HW_Gang/tree/master/Session0_HW

**Comment by Serinnnnn** [comment]
1. 홍세린
2. https://github.com/Serinnnnn/Session0_HW

**Comment by extrajunwan** [comment]
1. 박준완
2. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session0_HW

**Comment by baby-crows** [comment]
1. 이영서
2. https://github.com/monator16/Likelion.practice/tree/master/Session0_HW

**Comment by fortepiano13** [comment]
1. 양휘민
2. https://github.com/fortepiano13/HW

**Comment by HaYoonsoo** [comment]
1. 하윤수
2. https://github.com/HaYoonsoo/likelion/tree/master/Session0_HW

**Comment by sonsoowon** [comment]
1. 손수원
2. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session0_HW

**Comment by kchaehyeon01** [comment]
1. 김채현
2. https://github.com/kchaehyeon01/NEXTLikeLion2022.git

**Comment by JHLvJz** [comment]
1. 문지후
2. https://github.com/JHLvJz/NxL2022/tree/master/Session0_HW

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/NextLikelion_HW

**Comment by dizolion** [comment]
1. 박소정
2. https://github.com/dizolion/skycolor10/tree/master/Session0_HW

**Comment by innerstella** [comment]
1. 차수지
2. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session0_HW

**Comment by ziw00** [comment]
1. 정지우
2. https://github.com/ziw00/LIKELION.git

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session0_HW

**Comment by reason-jinny** [comment]
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion.git

**Comment by jisoolee0929** [comment]
1. 이지수
2. https://github.com/jisoolee0929/NEXTLION/tree/master/Session0_HW
