### ISSUE TITLE
[NEXT 10th Assignment] Session 1 - HTML&CSS 기초

### ISSUE THREAD

**Issue by gadongkim** [NEXT-LIKELION/2022-NEXT-Assignment#2]
## 📌 3/17 세션 전까지 댓글로 과제 인증해주세요 !

* 코드카데미 Learn HTML / Learn CSS 수강
* HTML & CSS로 내 자기 소개 페이지 제작하기

## [댓글 업로드 예시]
1. 이름
2. 과제 깃헙 링크
	: session1 폴더 안에 자기소개 페이지 html/css 파일, 코드카데미 수강 완료 인증 캡처본
3. 제작한 자기소개 페이지 캡처 이미지

📌 3/21 세션 전까지 [코딩애플](https://codingapple.com)의 <빠르게 정리하는 파이썬 기초 문법>을 수강해주세요.

**Comment by eauchan** [comment]
1. 이의찬
2. https://github.com/eauchan/Next_LikeLion/tree/main/Session1_HW
3.
<img width="941" alt="자기소개 홈페이지 1" src="https://user-images.githubusercontent.com/91827518/158372792-7708b0fa-2749-49f2-9d4a-cf2a884f6941.PNG">
<img width="929" alt="자기소개 홈페이지 2" src="https://user-images.githubusercontent.com/91827518/158372801-f2abf777-0f53-4233-8d28-514b369be7da.PNG">
<img width="931" alt="자기소개 홈페이지 3" src="https://user-images.githubusercontent.com/91827518/158372809-d76c4e4a-593b-4bcc-9b9e-0881d46fa3d8.PNG">
<img width="935" alt="자기소개 홈페이지 4" src="https://user-images.githubusercontent.com/91827518/158372814-c54967cf-de5b-404e-9679-40063df955da.PNG">

**Comment by Park747** [comment]
1. 박견우
2. https://github.com/Park747/Likelion-Assignment/tree/master/session1
3.
![자기소개 캡쳐1](https://user-images.githubusercontent.com/101241978/158536245-309861fc-58b0-4bf8-bae1-5fdd4a37a7bb.png)
![자기소개캡쳐 2](https://user-images.githubusercontent.com/101241978/158536256-53058035-b38a-44e8-b426-a4ccb79fbcdf.png)
![자기소개 캡쳐3](https://user-images.githubusercontent.com/101241978/158536261-bd79798a-8936-4e1a-b4b9-bc3e85804752.png)
![자기소개캡쳐 4](https://user-images.githubusercontent.com/101241978/158536290-6714bd9b-7fe5-447c-9295-a3159bd38013.png)

**Comment by innerstella** [comment]
1. 차수지
2. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session1_HW
3.
<img width="960" alt="page" src="https://user-images.githubusercontent.com/77491430/158611544-7793e054-8bf9-419a-af66-58c268ae6354.png">

**Comment by notaonce** [comment]
1. 한성수
2. https://github.com/notaonce/Assignment1.git
3. 
![웹페이지1](https://user-images.githubusercontent.com/87408958/158623406-1335d5fd-af92-4032-9b3a-feb680e40b21.png)
![웹페이지1-1](https://user-images.githubusercontent.com/87408958/158623413-f1b8c9bc-d674-4cda-a075-9902f9e45b0a.png)
![웹페이지2](https://user-images.githubusercontent.com/87408958/158623422-2c9533bc-bfb1-4d43-837f-83a91301c24a.png)
![웹페이지3](https://user-images.githubusercontent.com/87408958/158623432-ce11e608-64d2-4e97-b0b0-949bf3a7a817.png)

**Comment by Canada-Joose** [comment]
1. 주장규
2. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session1_HW
3.
![스크린샷 2022-03-17 오전 1 08 56](https://user-images.githubusercontent.com/100463676/158635964-490f9d91-9c7e-49ff-8e75-f1515ce035ac.png)
![스크린샷 2022-03-17 오전 1 09 09](https://user-images.githubusercontent.com/100463676/158635986-65f8a634-81bc-4065-845f-46810a5edd65.png)
![스크린샷 2022-03-17 오전 1 09 18](https://user-images.githubusercontent.com/100463676/158636008-6b170de5-d314-485c-8473-9785072d2356.png)

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session1_HW
3. *html을 링크로 연결해서 세 가지 독립적인 화면입니다!
<img width="519" alt="스크린샷 2022-03-17 오전 1 44 41" src="https://user-images.githubusercontent.com/89579178/158643216-ee027a8a-f6a5-42cc-b397-38e9851a1e9b.png">
<img width="597" alt="스크린샷 2022-03-17 오전 1 45 59" src="https://user-images.githubusercontent.com/89579178/158643255-c64cf4c8-0e37-4125-8143-5268bd006732.png">
<img width="601" alt="스크린샷 2022-03-17 오전 1 45 32" src="https://user-images.githubusercontent.com/89579178/158643264-6f8176de-0f96-4e5f-84d6-860d3c12cbff.png">

**Comment by extrajunwan** [comment]
1. 박준완
2. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session1_HW
3.
<img width="1440" alt="스크린샷 2022-03-17 오전 2 46 57" src="https://user-images.githubusercontent.com/101266326/158654533-268c137d-8598-465e-b46b-2c629756503f.png">

**Comment by Moi1oM** [comment]
1.전성운
2.https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session1_HW
3![image01](https://user-images.githubusercontent.com/101260709/158662223-397dc7f8-ae77-483c-a910-597fcda95469.png)
![image02](https://user-images.githubusercontent.com/101260709/158662207-69cd42ea-d9ad-4ee4-b843-bfced02c69cb.png)
![image03](https://user-images.githubusercontent.com/101260709/158662215-e8cb2c59-7e09-4f2f-823d-63f8020e1586.png)
![image04](https://user-images.githubusercontent.com/101260709/158662217-abe05fac-e72e-4ae2-bc58-1526fad31583.png)

**Comment by sde0116** [comment]
1. 서다은
2. https://github.com/sde0116/NextLikelion/tree/master/Session1_HW
3.
![Webpage](https://user-images.githubusercontent.com/101265923/158701111-f820a7f2-744b-49cb-ad09-499838b01fa1.png)

**Comment by toyo30** [comment]
1. 백민기
2. https://github.com/toyo30/next-like-lion/tree/main/Session01_HW/self-intro
3.

**Comment by toyo30** [comment]
1. 백민기
2. https://github.com/toyo30/next-like-lion/tree/main/Session01_HW/self-intro
3. 
https://user-images.githubusercontent.com/55613446/158723546-61931d7b-fa11-4068-ad74-59d3a66a01c6.mp4

전체 페이지
https://toyo30.github.io/next-like-lion/Session01_HW/self-intro/self-intro.html
(로딩이 45초 정도 걸립니다 ㅠㅜ)

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/
3. 
<img width="1439" alt="스크린샷 2022-03-17 오전 11 50 02" src="https://user-images.githubusercontent.com/101280374/158727605-6002445e-7d47-4a1e-b15e-dbeaf1db9ef0.png">
master/Session01_HW
<img width="1440" alt="스크린샷 2022-03-17 오전 11 50 21" src="https://user-images.githubusercontent.com/101280374/158727635-1e16b134-7e3f-4c38-930a-47fb5999ff3d.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 50 34" src="https://user-images.githubusercontent.com/101280374/158727659-bb286798-9902-47a6-bd0c-7011a617944a.png">
<img width="1438" alt="스크린샷 2022-03-17 오전 11 50 46" src="https://user-images.githubusercontent.com/101280374/158727670-f2576512-b4bf-47ea-a185-2bc4e1cae426.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 50 57" src="https://user-images.githubusercontent.com/101280374/158727690-e3c9cf66-9e2e-4c4f-b6bf-1ecf2ef2cc5d.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 51 10" src="https://user-images.githubusercontent.com/101280374/158727699-c46835b4-4692-409b-a8a1-83212070b8bf.png">
<img width="1434" alt="스크린샷 2022-03-17 오전 11 51 24" src="https://user-images.githubusercontent.com/101280374/158727727-c97491cb-4f13-4cc5-bc95-54b732935964.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 51 36" src="https://user-images.githubusercontent.com/101280374/158727746-e946e2f5-6a65-4e89-81e4-cd7eda4c2941.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 51 46" src="https://user-images.githubusercontent.com/101280374/158727754-6b665534-55d9-416b-b221-b18119d019f2.png">
<img width="1440" alt="스크린샷 2022-03-17 오전 11 52 00" src="https://user-images.githubusercontent.com/101280374/158727767-6b2a67d1-afbd-4eb4-999b-807caf526239.png">

**Comment by CryingDitto** [comment]
1. 이지은
2. https://github.com/CryingDitto/NextLionX/tree/master/Session01_HW
3. 
![화면 캡처 2022-03-17 130041](https://user-images.githubusercontent.com/101262081/158735655-d4501875-d52a-4021-aa15-a85ae207dec8.png)
![화면 캡처 2022-03-17 130104](https://user-images.githubusercontent.com/101262081/158735673-e142978d-ad21-43fc-9792-a70808126a7d.png)

**Comment by alswlalswl1013** [comment]
1. 김민지
2. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session1_HW
3. 
<img width="869" alt="1" src="https://user-images.githubusercontent.com/101307543/158742557-fec82cff-1f6d-4983-a592-57b9d060715a.PNG">
<img width="883" alt="2" src="https://user-images.githubusercontent.com/101307543/158742562-e26f80ba-4f7e-4ba5-8112-4c55e35c0b81.PNG">
<img width="904" alt="3" src="https://user-images.githubusercontent.com/101307543/158742564-3f8d1cf8-0107-4dc1-b811-0329b1b76cee.PNG">
<img width="920" alt="4" src="https://user-images.githubusercontent.com/101307543/158742567-8e7ecdde-9dec-4000-9c74-71c0ac201a9e.PNG">
<img width="907" alt="5" src="https://user-images.githubusercontent.com/101307543/158742571-afa01e20-9913-4168-acc1-a6c231a178d4.PNG">

**Comment by ssoy0514** [comment]
1. 이소희
2. https://github.com/ssoy0514/NEXTxLIKELION.git
3.
![AboutMe](https://user-images.githubusercontent.com/101264437/158743436-8150bc45-58c2-4b66-b6c9-776e5ce86fcf.png)

**Comment by seoulmango** [comment]
1. 박기만
2. https://github.com/seoulmango/Likelion2022_HW/tree/master/Session01_HW
3.  첨부
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 14" src="https://user-images.githubusercontent.com/93420605/158753360-2439d061-2636-41f6-a17b-733c91576602.png">
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 24" src="https://user-images.githubusercontent.com/93420605/158753376-96458bb3-2abe-42c9-8409-514ff27e54c8.png">
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 32" src="https://user-images.githubusercontent.com/93420605/158753394-fdafb793-f9bf-43a4-981d-a242d652e34a.png">
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 40" src="https://user-images.githubusercontent.com/93420605/158753408-9418b373-bf3d-452c-bfd1-8a4db408b30c.png">
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 46" src="https://user-images.githubusercontent.com/93420605/158753431-61ec23eb-50d6-48f5-8706-c1b6072be2f8.png">
<img width="1440" alt="스크린샷 2022-03-17 오후 3 51 53" src="https://user-images.githubusercontent.com/93420605/158753453-1f6e9ee7-3b3d-4d09-baf3-2995db16648e.png">

**Comment by ghost** [comment]
1. 김지욱
2. https://github.com/ziweek/likelion/tree/master/Assignments/Session1_HW
3. 
<img width="1277" alt="main" src="https://user-images.githubusercontent.com/99459331/158762049-3b419ad6-381d-4606-b640-aa1bb20a34d5.png">

**Comment by dizolion** [comment]
1. 박소정
2. https://github.com/dizolion/skycolor10/tree/master/Session1
3. 
![image](https://user-images.githubusercontent.com/101280974/158765490-d2e26234-e8c2-46e2-93ca-f137337cc159.png)
![image](https://user-images.githubusercontent.com/101280974/158765560-3413e8e0-a3fb-45d4-87d3-d1f5a483c749.png)
![image](https://user-images.githubusercontent.com/101280974/158765624-09752c9d-0433-41a2-8f44-b1ede6245257.png)
![image](https://user-images.githubusercontent.com/101280974/158765669-57e15262-fafe-4409-bc64-6ccca4d79468.png)
![image](https://user-images.githubusercontent.com/101280974/158765737-fb1a1883-8674-4495-b43e-dca4315d54c6.png)
![image](https://user-images.githubusercontent.com/101280974/158765845-a7af8527-0ed0-4cc2-a4d1-98548617a235.png)

**Comment by jisoolee0929** [comment]
1. 이지수
2. https://github.com/jisoolee0929/NEXTLION/tree/master/Session1_HW
3.
![캡처1](https://user-images.githubusercontent.com/62417326/158766331-aeb16bea-98e0-4d4d-b895-89e190332528.PNG)
![캡처2](https://user-images.githubusercontent.com/62417326/158766378-58e787e1-561c-49c7-bf5d-2ee2cc600a8e.PNG)
![캡처3](https://user-images.githubusercontent.com/62417326/158766401-f10dc34b-ff0e-47a3-bb09-3aad0843de32.PNG)

**Comment by 99rbbt** [comment]
1.신재현
2.https://github.com/99rbbt/Nextlion2022/tree/master/Session1_HW
3
![자기소개1](https://user-images.githubusercontent.com/101272544/158767355-e58b93cc-e584-4d15-bb2d-315472b165f4.jpg)
![자기소개2](https://user-images.githubusercontent.com/101272544/158767357-8ba8a83d-6b73-477f-be53-fe5b93fc650f.jpg)
.

**Comment by fortepiano13** [comment]
1. 양휘민
2. https://github.com/fortepiano13/HW/tree/main/Session1_HW
3. 
![화면 캡처 2022-03-17 172214](https://user-images.githubusercontent.com/101318912/158768750-2a73b5a4-ce84-48b2-8c0b-9a2f77a6f6aa.png)

**Comment by sonsoowon** [comment]
1. 손수원
2. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session1_HW
3.
![1](https://user-images.githubusercontent.com/55790232/158769717-e7f3b59c-fd97-48d9-99a1-1cb9504e4450.png)
![2](https://user-images.githubusercontent.com/55790232/158769721-01e74d97-b11c-4788-8f75-928fce1a9f4f.png)
![3](https://user-images.githubusercontent.com/55790232/158769723-df65ec18-8b6b-4700-89b0-98ae757312bb.png)

**Comment by nymvmt** [comment]
1. 김나영
2. https://github.com/nymvmt/Next_Likelion_2022/tree/master/Session1_HW
3.
<img width="1147" alt="스크린샷 2022-03-17 오후 5 41 14" src="https://user-images.githubusercontent.com/99931269/158770795-0dee3ea1-40be-40c8-90e6-0ac3db1f2696.png">
<img width="1153" alt="스크린샷 2022-03-17 오후 5 40 52" src="https://user-images.githubusercontent.com/99931269/158770814-b2163a31-7d8c-40a0-b0dc-ec4d02d8855c.png">
<img width="1153" alt="스크린샷 2022-03-17 오후 5 40 42" src="https://user-images.githubusercontent.com/99931269/158770824-5cf8bbf9-cf7f-4d3f-8f00-4651a432843d.png">

**Comment by kchaehyeon01** [comment]
1. 김채현
2. https://github.com/kchaehyeon01/NEXTLikeLion2022.git
3. 
![image](https://user-images.githubusercontent.com/80916105/158777279-2b94bf1a-6597-401c-82de-f893b20f4b68.png)

**Comment by onelee812** [comment]
1. 이예원
2. https://github.com/onelee812/LikeLion22/tree/main/Session1_HW
3.
<img width="969" alt="Screen Shot 2022-03-17 at 6 23 21 PM" src="https://user-images.githubusercontent.com/98938138/158778610-b41d1262-70d7-4950-b713-24f7d25da65b.png">
<img width="635" alt="Screen Shot 2022-03-17 at 6 23 30 PM" src="https://user-images.githubusercontent.com/98938138/158778641-ea833d89-a6ed-46d7-81b4-80893241783d.png">

**Comment by sophiahyj** [comment]
1. 한예진
2. https://github.com/sophiahyj/likelionHW/tree/master/Session1_HW
3
![KakaoTalk_20220317_182550396](https://user-images.githubusercontent.com/101271670/158779483-dd44acc5-4d49-47e7-b028-b8ffcb2ff955.png)
![KakaoTalk_20220317_182554469](https://user-images.githubusercontent.com/101271670/158779502-257f8c12-cf47-4795-8de5-2ac7ca97370d.png)
.

**Comment by HaYoonsoo** [comment]
1. 하윤수
2. https://github.com/HaYoonsoo/likelion/tree/master/Session1_HW
3.
![스크린샷 2022-03-17 오후 6 44 11](https://user-images.githubusercontent.com/101256025/158782299-3e9a7e56-b842-4b57-a69b-52c886f8db1a.png)
![스크린샷 2022-03-17 오후 6 44 24](https://user-images.githubusercontent.com/101256025/158782274-a52dff40-5b32-406e-b1f1-40db7a1568ff.png)

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session1
3.
<img width="1440" alt="엄혜영 페이지2" src="https://user-images.githubusercontent.com/99478871/158782757-4de86ff0-3648-4a13-bd0c-316fae3d1dad.png">
<img width="1440" alt="엄혜영 페이지1" src="https://user-images.githubusercontent.com/99478871/158782738-23809302-4f06-4d4e-a33a-0a074dc63224.png">

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/NextLikelion_HW
3.
![1](https://user-images.githubusercontent.com/101259370/158782894-fb47b8d6-c245-4cf3-a533-e1bb647f434c.JPG)
![2](https://user-images.githubusercontent.com/101259370/158782901-f260d98f-c845-47a6-82bc-2060c1caaa70.JPG)
![3](https://user-images.githubusercontent.com/101259370/158782903-c2720f20-c72c-46be-9e48-c041e0bff3e5.JPG)
![4](https://user-images.githubusercontent.com/101259370/158782907-90a8727a-1890-457d-84d9-7cfe813ab3de.JPG)

**Comment by willbeagangsta** [comment]
1. 김하경
2. https://github.com/willbeagangsta/NEXT_LikeLion_HW_Gang
3. 
![Website2 (2)](https://user-images.githubusercontent.com/101272176/158783490-30301c85-14b4-4719-a59f-424949b704dd.PNG)
![Website2](https://user-images.githubusercontent.com/101272176/158783505-52ef7645-ac32-4bbe-b3f4-80b104b215b8.PNG)

**Comment by JHLvJz** [comment]
1. 문지후
2. https://github.com/JHLvJz/NxL2022/tree/master/Session1_HW
3.
<img width="1423" alt="hw2" src="https://user-images.githubusercontent.com/101316991/158963636-1dac8a57-89cd-427e-977f-0ead928a30d4.png">
<img width="1434" alt="hw2_" src="https://user-images.githubusercontent.com/101316991/158784597-3e64227b-e586-48cd-b2ca-122e13806107.png">

**Comment by Serinnnnn** [comment]
1. 홍세린
2. https://github.com/Serinnnnn/LIKELION-HW-.git
3.
<img width="1230" alt="스크린샷 2022-03-17 오후 7 04 37" src="https://user-images.githubusercontent.com/101257662/158785822-49aa8f19-b65e-45d9-9315-dd8ff528de9c.png">
<img width="1130" alt="스크린샷 2022-03-17 오후 7 04 52" src="https://user-images.githubusercontent.com/101257662/158785847-1fe2b209-a40d-4644-a33a-741e3bc13a94.png">

**Comment by baby-crows** [comment]
이거는 해놓고 올린다는 걸 까먹고 있었네요 ㅠㅠ!! 죄송합니다. 뒤늦게나마 제출해요!
1. 이영서
2. https://github.com/monator16/Likelion.practice/tree/main/Session1_HW
3. 

![image](https://user-images.githubusercontent.com/101310701/163111994-3382afc6-1dd4-485a-b6ff-8151ca05b532.png)
![20220413_15145738](https://user-images.githubusercontent.com/101310701/163112156-cc0df658-c93f-419a-9ec1-050bdaa4391f.png)

**Comment by reason-jinny** [comment]
첫 번째 과제를 했다는 생각에 세션 0 과제와 헷갈려서 세션 1 과제 존재 자체를 잊어버린 멍청이입니다.. 죄송합니다😭 MT에서 뵈어요!!
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session1_HW
3.

https://user-images.githubusercontent.com/101304885/166624335-7c5d0300-c5b9-4bf6-a61d-7bf267201f1c.mov
