### ISSUE TITLE
[NEXT 10th Assignment] Session 2 - CSS 심화

### ISSUE THREAD

**Issue by jiyoon27** [NEXT-LIKELION/2022-NEXT-Assignment#4]
### **3/21 세션 전까지 댓글로 과제 인증해주세요!**

- HTML/CSS로 인스타그램 클론 코딩
- 코딩애플 <빠르게 정리하는 파이썬 기초 문법> 수강

### **[과제 업로드 예시]**

1. 이름
2. 과제 깃헙 링크

- session2 폴더 안에 인스타그램 클론 코딩 html/css 파일, 인스타그램 클론 코딩 캡쳐 이미지, 코딩애플 수강 완료 인증 캡쳐 이미지

3. 인스타그램 클론 코딩 과제 캡쳐 이미지
4. 코딩애플 수강 완료 인증 캡쳐 이미지

**Comment by Park747** [comment]
1. 박견우
2.  https://github.com/Park747/Likelion-Assignment/tree/master/session2_HW
3.
![클론코딩](https://user-images.githubusercontent.com/101241978/158959349-5f040126-3def-418c-b868-a8b53dad1f17.png)

4.
![코딩애플 수강캡쳐본](https://user-images.githubusercontent.com/101241978/158958302-741d576f-0294-46a2-b993-0b78806dcf0e.png)

**Comment by Canada-Joose** [comment]
1. 주장규
2. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session2_HW
3. 인스타그램 클론 코딩 과제 캡쳐 이미지

![스크린샷 2022-03-18 오후 11 00 49](https://user-images.githubusercontent.com/100463676/159018491-7a4c4eb2-7d1b-443e-9c55-10dd78d88b4a.png)

4. 코딩애플 수강 완료 인증 캡쳐 이미지

![python_수강](https://user-images.githubusercontent.com/100463676/159018530-62c4d314-b369-4eaa-a1bc-0a38a5ce812b.png)

**Comment by toyo30** [comment]
1. 백민기
2. [과제 깃헙 링크](https://github.com/toyo30/next-like-lion/tree/main/Session02_HW)
3. 
![100_07i2](https://user-images.githubusercontent.com/55613446/159103374-e59b020e-f8b6-489f-b724-57ef24d99a72.png)
4. 
![Pasted Graphic 4](https://user-images.githubusercontent.com/55613446/159103390-5ca0421c-f16d-4b07-bf7f-6cb3d60c456a.png)

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session2_HW
3.
<img width="1059" alt="인스타그램" src="https://user-images.githubusercontent.com/89579178/159110415-8955915a-febb-40cd-973c-fa1e9599eb70.png">
4. 
<img width="1440" alt="강의 수강 완료" src="https://user-images.githubusercontent.com/89579178/159110422-38d6eabd-a80a-43b5-a96e-7b2b60ae2ce9.png">

**Comment by Moi1oM** [comment]
1. 전성운
2.https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session2_HW
3.
![image](https://user-images.githubusercontent.com/101260709/159110409-62734c43-9034-428b-9c37-6b0805a1ab89.png)
![image](https://user-images.githubusercontent.com/101260709/159110418-35d8f47e-e877-4434-a0a5-7984c14ac455.png)
4.
![image](https://user-images.githubusercontent.com/101260709/159110428-5bc14abe-86c4-4537-bf77-3eba966d1ebd.png)

**Comment by notaonce** [comment]
1. 한성수
2. https://github.com/notaonce/Assignment1.git
3.
![인스타클론캡처](https://user-images.githubusercontent.com/87408958/159113034-3302876a-98a2-432a-9421-7d36c912b9fd.png)
4. 
![수강완료](https://user-images.githubusercontent.com/87408958/159113035-ab2d814c-da67-4b4d-9835-419c625f2532.png)

**Comment by sde0116** [comment]
1. 서다은
2. https://github.com/sde0116/NextLikelion/tree/master/Session_HW/Session2_HW
3.
![Clone_Coding instagram](https://user-images.githubusercontent.com/101265923/159117197-f44401d3-ad63-4842-8ff9-2f4bdb754122.png)

4.
![코딩애플 파이썬](https://user-images.githubusercontent.com/101265923/159117194-4ab236c1-2882-4591-82aa-9b950ded7f66.png)

**Comment by innerstella** [comment]
1. 차수지
2. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session2_HW
3.
<img width="239" alt="instagram" src="https://user-images.githubusercontent.com/77491430/159120319-0299db67-7b08-4224-bf7c-4f7a3677855e.png">
4. 
<img width="960" alt="python" src="https://user-images.githubusercontent.com/77491430/159120323-893f18de-4c8f-4afc-9269-e3becb3a93b7.png">

**Comment by seoulmango** [comment]
1. 박기만
2. https://github.com/seoulmango/Likelion2022_HW/tree/master/Session02_HW
3.
![Instagram_Clone](https://user-images.githubusercontent.com/93420605/159122468-3282f74d-aaf6-42d5-af13-fd19304c392a.png)

4.
<img width="1440" alt="스크린샷 2022-03-19 오후 10 10 49" src="https://user-images.githubusercontent.com/93420605/159122518-0c519f47-4321-460d-8748-b44b80461f6e.png">

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session2_HW
3.
![스크린샷 2022-03-20 오전 5 23 35](https://user-images.githubusercontent.com/99478871/159137430-8fe2dda1-2910-4b24-9a98-59fabde13141.png)
4. ![엄혜영 코딩애플 파이썬 기초강좌 수강 인증샷](https://user-images.githubusercontent.com/99478871/159137448-d851409e-e647-4530-b0a9-551eda4f86f1.png)

**Comment by toyo30** [comment]
1. 백민기
2. https://github.com/toyo30/next-like-lion/tree/main/Session02_HW
3. 인스타그램 클론 코딩 과제 캡쳐 이미지 
![100_07i2](https://user-images.githubusercontent.com/55613446/159149585-aa43bf77-4312-4dbd-9edb-aa3e96f4f622.png)
4. 코딩애플 수강 완료 인증 캡쳐 이미지
![Pasted Graphic 4](https://user-images.githubusercontent.com/55613446/159149594-9fde24ea-8fc1-49d9-b0f3-1435069f8a5a.png)

**Comment by CryingDitto** [comment]
1. 이지은
2. https://github.com/CryingDitto/NextLionX/tree/master/Session02_HW
3.
![captureImage](https://user-images.githubusercontent.com/101262081/159158233-8cc2f3c8-d5f4-4dfb-acd8-7bc0be6debcb.png)
4.
![image](https://user-images.githubusercontent.com/101262081/159158258-e1e95dd6-92ae-4c0e-a9c4-17d51f56fff0.png)

**Comment by HaYoonsoo** [comment]
1. 하윤수
2. https://github.com/HaYoonsoo/likelion/tree/master/Session2_HW
3.
![인스타그램](https://user-images.githubusercontent.com/101256025/159160909-27c955c1-aae0-4930-b56d-27ed711d1bee.png)
4.
![코딩애플 수강완료](https://user-images.githubusercontent.com/101256025/159160917-26ddcbe6-f357-43fc-8616-0497350f08a2.png)

**Comment by alswlalswl1013** [comment]
1. 김민지
2. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session2_HW
3.
<img width="314" alt="인스타그램 클론코딩_김민지" src="https://user-images.githubusercontent.com/101307543/159162250-6fe36d59-8a82-4204-8670-4bb4d316691a.PNG">
<img width="949" alt="코딩애플 수강 화면_김민지" src="https://user-images.githubusercontent.com/101307543/159162252-2b31eb20-db6c-4a4a-b8b7-c0f7d7f00faf.PNG">

**Comment by ssoy0514** [comment]
1. 이소희
2. https://github.com/ssoy0514/NextxLikelion-HW.git
3.
![코딩애플 수강 인증](https://user-images.githubusercontent.com/101264437/159170074-8a695927-27f0-4615-8759-784852eb0ea9.png)
![KakaoTalk_20220320_183533555](https://user-images.githubusercontent.com/101264437/159170185-48e92c5c-4054-4fd3-8abd-fa608e794601.png)

**Comment by extrajunwan** [comment]
1. 박준완
2. https://github.com/extrajunwan/N
3. 
<img width="451" alt="스크린샷 2022-03-21 오전 1 00 09" src="https://user-images.githubusercontent.com/101266326/159171199-f2561f4f-4d36-44d8-a5d9-69de3d8e66a5.png">
4. 
<img width="341" alt="코딩애플 수강완료 인증 캡쳐 이미지" src="https://user-images.githubusercontent.com/101266326/159171131-fbf494d9-01cc-4892-a94e-b087a6676e83.png">

**Comment by Serinnnnn** [comment]
1. 홍세린
2. https://github.com/Serinnnnn/LIKELION-HW-.git
3.
<img width="373" alt="스크린샷 2022-03-21 오전 1 10 35" src="https://user-images.githubusercontent.com/101257662/159171658-c1a5cfdd-cd03-4f6c-a26e-f8efede62a07.png">
4.
<img width="353" alt="파이썬 강의 인증" src="https://user-images.githubusercontent.com/101257662/159171682-ac2379a3-6418-4d86-a3a8-f0d09836c46f.png">

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session02_HW
3. 
<img width="377" alt="송명훈 인스타그램 클론코딩 결과물" src="https://user-images.githubusercontent.com/101280374/159172527-2802192c-9bd8-475d-a01e-7570bc68f
4. 
<img width="351" alt="송명훈 코딩애플 수강인증" src="https://user-images.githubusercontent.com/101280374/159172546-91e04e55-dd79-49ba-9878-a46082642d16.png">
e05.png">

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session02_HW
3.
<img width="377" alt="송명훈 인스타그램 클론코딩 결과물" src="https://user-images.githubusercontent.com/101280374/159172611-6422a2b6-b3ef-4f4a-8d52-a7e0749f4163.png">
4.
<img width="351" alt="송명훈 코딩애플 수강인증" src="https://user-images.githubusercontent.com/101280374/159172625-17bc08c8-5461-473d-963d-fc7d52120691.png">

**Comment by 99rbbt** [comment]
1. 신재현
2. https://github.com/99rbbt/Nextlion2022/tree/master/Session2_HW
3.
![instacopy](https://user-images.githubusercontent.com/101272544/159175218-9f7d3617-b57d-47c4-a874-3da4f397aa31.jpg)
4.
![화면 캡처 2022-03-19 010242](https://user-images.githubusercontent.com/101272544/159175228-6d809216-6ec2-42c7-bf0b-a17f33224279.jpg)

**Comment by willbeagangsta** [comment]
1. 김하경
2. https://github.com/willbeagangsta/Next_Lion_Gang/tree/master/Homeworks/Session2_HW
3.
![insta](https://user-images.githubusercontent.com/101272176/159175980-320d432c-8d60-4b14-bc0d-95c62afa1827.PNG)
![코딩애플](https://user-images.githubusercontent.com/101272176/159175984-9b1c2917-05d7-41b0-b56c-505cd5de920b.PNG)

**Comment by eauchan** [comment]
1. 이의찬
2. https://github.com/eauchan/Next_LikeLion/tree/main/Session2_HW
3.
<img width="214" alt="인스타그램 클론코딩 캡처" src="https://user-images.githubusercontent.com/91827518/159184431-d6122540-8bc7-4fc7-b2d9-ede6c2b9e2b9.PNG">
<img width="945" alt="코딩애플 수강 완료 캡처" src="https://user-images.githubusercontent.com/91827518/159184437-529758b2-0c39-4e93-ae49-1d480a4d937f.PNG">

**Comment by dizolion** [comment]
1. 박소정
2. 
3. ![image](https://user-images.githubusercontent.com/101280974/159187689-197c64cf-e8fa-4818-b562-84551c7945cc.png)
4. ![코딩애플 수강 완료 인증샷](https://user-images.githubusercontent.com/101280974/159187656-ff0834c7-74c3-4932-a649-abd47cdf035c.PNG)

**Comment by onelee812** [comment]
1. 이예원 
2. https://github.com/onelee812/LikeLion22/tree/main/Session2_HW
3.
![인스타그램 클론 코딩 과제 캡쳐 이미지](https://user-images.githubusercontent.com/98938138/159205435-f13abd84-4f06-4b53-a078-dca109cceac5.jpg)
4. 
<img width="1367" alt="코딩애플 수강 완료 인증 캡쳐 이미지" src="https://user-images.githubusercontent.com/98938138/159205445-86e9c935-dcad-4e84-9d64-2f3d091d1e20.png">

**Comment by nymvmt** [comment]
1. 김나영
2. https://github.com/nymvmt/Next_LikeLion_2022/tree/master/Session2_HW
3.
<img width="516" alt="ScreenShot  Instagram_1" src="https://user-images.githubusercontent.com/99931269/159209871-12f52e65-503d-421b-a44d-4f8b7ed397c5.png">
<img width="517" alt="ScreenShot  Instagram_2" src="https://user-images.githubusercontent.com/99931269/159209887-85ff6494-99ae-4ad3-97c4-6e1032bf1219.png">
4. 
<img width="1440" alt="Python_ CodingApple_100%" src="https://user-images.githubusercontent.com/99931269/159209898-bec51735-faa6-4b5c-a917-b2cd1c94debd.png">

**Comment by sonsoowon** [comment]
1. 손수원
2. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session2_HW
3. 
![capture1](https://user-images.githubusercontent.com/55790232/159212822-0ccca012-43e0-43c4-9532-df542aaa768b.png)

![capture2](https://user-images.githubusercontent.com/55790232/159212826-8d1a8f1a-cc59-426e-8d70-ad4f71c5f391.png)

4.
![class](https://user-images.githubusercontent.com/55790232/159212827-7b275ab2-5e0f-48b4-b9b5-af0cff619461.png)

**Comment by jisoolee0929** [comment]
1. 이지수
2. https://github.com/jisoolee0929/NEXTLION/tree/master/Session2_HW
3.
![capture](https://user-images.githubusercontent.com/62417326/159217310-c4a4da1e-14e4-47d7-bb9e-e9a16cbbec9d.PNG)
4. 
![capture2](https://user-images.githubusercontent.com/62417326/159217332-4a337876-ae5b-473d-8062-2afe47f47b74.PNG)

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/2022-1-NextLikelion-HW_2
3.
![instagram](https://user-images.githubusercontent.com/101259370/159227034-6401f521-4cef-441a-b959-5a91f177c9cb.jpg)

4. 
![codingapple(phyton)_yoon](https://user-images.githubusercontent.com/101259370/159227095-c250bed7-b4cc-4816-9d9a-7fb3c2a75f09.JPG)

**Comment by kchaehyeon01** [comment]
1. 김채현
2. https://github.com/kchaehyeon01/NEXTLikeLion2022.git
3. 
![image](https://user-images.githubusercontent.com/80916105/159227328-dbbbd45c-f664-442b-a425-afa5bf3b35d7.png)
4.
<img width="960" alt="코딩 애플 수강" src="https://user-images.githubusercontent.com/80916105/159227346-8c7b3562-1a36-470c-91f9-ca326d4199d8.png">

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/2022-1-NextLikelion-HW_2
3.
![instagram 2](https://user-images.githubusercontent.com/101259370/159227472-3ab182a7-9b2d-490a-b068-f2616e81a58c.jpg)
4.
![codingapple(phyton)_yoon](https://user-images.githubusercontent.com/101259370/159227482-1a1d83ca-4a45-4dcc-8ff0-d3d4349b0dff.JPG)

**Comment by JHLvJz** [comment]
1. 문지후
2. https://github.com/JHLvJz/NxL2022 
3.
<img width="380" alt="클론코딩캡쳐" src="https://user-images.githubusercontent.com/101316991/159231512-7a5abd58-099c-4984-a91a-5f8273da7885.png">
4. 
<img width="1212" alt="코딩애플파이썬" src="https://user-images.githubusercontent.com/101316991/159231577-9c8df34c-5b0a-4182-b3f6-dc2d38b39810.png">

**Comment by sophiahyj** [comment]
1. 한예진
2. https://github.com/sophiahyj/likelionHW/tree/master/Session2_HW
3. ![homework](https://user-images.githubusercontent.com/101271670/159232667-708fd864-a56e-4329-8704-85b1791c49e7.PNG)
![screenshot](https://user-images.githubusercontent.com/101271670/159232727-7eb0cad6-f6fb-49e2-bd91-afbeada53f51.png)

**Comment by ziw00** [comment]
1. 정지우
2. https://github.com/ziw00/LIKELION/blob/main/instagram.html
3.
<img width="473" alt="인스타그램 클론" src="https://user-images.githubusercontent.com/101320633/159236907-f6f38c09-0889-421f-b702-f90dbc3e43a9.png">
4. 
<img width="1416" alt="스크린샷 2022-03-21 14 44 12" src="https://user-images.githubusercontent.com/101320633/159237066-e721e827-5d2b-4c1a-b897-c5686ddba9e4.png">

**Comment by fortepiano13** [comment]
1. 양휘민
2. https://github.com/fortepiano13/HW/tree/main/Session2_H
<img width="452" alt="화면 캡처 2022-03-21 152607" src="https://user-images.githubusercontent.com/101318912/159239521-3d2e9105-b99f-46fe-811c-30b82751cab3.png">
W
<img width="536" alt="image" src="https://user-images.githubusercontent.com/101318912/159239707-ea711917-e2a5-4b1f-90a2-678b43ebd71a.png">

**Comment by baby-crows** [comment]
1. 이영서
2. https://github.com/monator16/Likelion.practice/tree/master/Session2_HW
3. 
![인스타클론코딩캡처화면](https://user-images.githubusercontent.com/101310701/159530034-4565af52-0f05-4114-9259-d355c5c9a1fe.PNG)

4.
![파이썬강좌수강](https://user-images.githubusercontent.com/101310701/159530092-be07a039-2448-4d93-aac4-37c786fa8909.PNG)

**Comment by reason-jinny** [comment]
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session2_HW
3.
<img width="1440" alt="인스타그램 클론 코딩" src="https://user-images.githubusercontent.com/101304885/163082124-a1375025-e671-4c31-bf37-d847d1d33abf.png">
4.
<img width="1440" alt="코딩애플 수강 완료 인증" src="https://user-images.githubusercontent.com/101304885/163082273-a6116704-6e41-4067-b0dd-eacbaf51ed52.png">
