### ISSUE TITLE
[NEXT 10th Assignment] Session 3 - 파이썬 기초

### ISSUE THREAD

**Issue by Kim-Jiseong** [NEXT-LIKELION/2022-NEXT-Assignment#5]
### [과제 업로드 예시]

1. 이름
2. 과제 깃헙 링크
3. session3 폴더 안에 hw1.py, hw2.py 파일을 올리고 링크를 달아주세요.

**Comment by HaYoonsoo** [comment]
1. 하윤수
2. https://github.com/HaYoonsoo/likelion/tree/master/Session3_HW(1)

**Comment by eauchan** [comment]
1. 이의찬
2. https://github.com/eauchan/Next_LikeLion/tree/main/Session3_HW

**Comment by Park747** [comment]
1.박견우
2.https://github.com/Park747/Likelion-Assignment/tree/master/session3_HW

**Comment by toyo30** [comment]
1. 백민기
2. https://github.com/toyo30/next-like-lion/tree/main/Session03_HW

**Comment by Canada-Joose** [comment]
1. 주장규
2. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session3_HW

**Comment by sonsoowon** [comment]
1. 손수원
2. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session3_HW

**Comment by CryingDitto** [comment]
1. 이지은
2. https://github.com/CryingDitto/NextLionX/tree/master/Session03_HW

**Comment by seoulmango** [comment]
1. 박기만
2. https://github.com/seoulmango/Likelion2022_HW/tree/master/Session03_HW

**Comment by Moi1oM** [comment]
1. 전성운
2. https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session3_HW

**Comment by nymvmt** [comment]
1. 김나영
2. https://github.com/nymvmt/Next_LikeLion_2022/tree/master/Session3_HW

**Comment by innerstella** [comment]
1. 차수지
2. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session3_HW

**Comment by jisoolee0929** [comment]
1. 이지수
2. https://github.com/jisoolee0929/NEXTLION/tree/master/Session3_HW

**Comment by sde0116** [comment]
1. 서다은
2. https://github.com/sde0116/NextLikeLion/tree/master/Session3_HW

**Comment by notaonce** [comment]
1. 한성수
2. https://github.com/notaonce/Assignment1.git

**Comment by fortepiano13** [comment]
1. 양휘민
2. https://github.com/fortepiano13/HW/tree/main/Session3_HW

**Comment by ziw00** [comment]
1. 정지우
2. https://github.com/ziw00/Session03_HW.git

**Comment by kchaehyeon01** [comment]
1. 김채현
2. https://github.com/kchaehyeon01/NEXTLikeLion2022/tree/master/Session3_HW

**Comment by dizolion** [comment]
1. 박소정
2. https://github.com/dizolion/skycolor10/tree/master/Session3

**Comment by willbeagangsta** [comment]
1. 김하경
2. https://github.com/willbeagangsta/Next_Lion_Gang

**Comment by 99rbbt** [comment]
1. 신재현
2. https://github.com/99rbbt/Nextlion2022/tree/master/Session3_HW

**Comment by ssoy0514** [comment]
1. 이소희
2. https://github.com/ssoy0514/NextxLikelion-HW.git

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session03_HW

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session3_HW

**Comment by Serinnnnn** [comment]
1.홍세린
2. https://github.com/Serinnnnn/LIKELION-HW-/tree/main/Session3/Session3_HW

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session3_HW

**Comment by JHLvJz** [comment]
1. 문지후
2. https://github.com/JHLvJz/NxL2022/tree/master/Session3_HW

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/Homeworks/tree/main/Session3_HW

**Comment by alswlalswl1013** [comment]
1. 김민지
2. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session3_HW

**Comment by extrajunwan** [comment]
1. 박준완
2. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session3_HW/%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EC%88%99%EC%A0%9C

**Comment by sophiahyj** [comment]
1. 한예진
2. https://github.com/sophiahyj/likelionHW/tree/master/Session3_HW

**Comment by onelee812** [comment]
1. 이예원 
2. https://github.com/onelee812/LikeLion22/tree/main/Session3_HW

**Comment by ghost** [comment]
1. 김지욱

2. https://github.com/ziweek/likelion/tree/master/Assignments/Session3_HW%20

**Comment by baby-crows** [comment]
1. 이영서
2. https://github.com/monator16/Likelion.practice/tree/master/Session3_HW

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session3_HW

**Comment by reason-jinny** [comment]
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session3
