### ISSUE TITLE
[NEXT 10th Assignment] Session 4 - 파이썬 심화

### ISSUE THREAD

**Issue by kulikelion** [NEXT-LIKELION/2022-NEXT-Assignment#6]

**Comment by pcw9341** [comment]
### 3/28일 세션 전까지 댓글로 과제 인증해주세요!
**[파이썬 심화 과제]**
>네이버 웹툰 크롤링

**[과제 업로드 예시]**

1. 이름
2. 과제 깃헙 링크

- session04 폴더 안에 webtoon.py 파일, main.py 파일, csv 파일, 에브리타임 클론 코딩 html/css 파일 총 5개 파일 업로드

3. 에브리타임 클론 코딩 캡쳐 화면

여러분 수고많으셨어요 ㅎ_ㅎ 우리 selenium공부도 꼭! ! 같이 해봐요

**Comment by Park747** [comment]
1. 박견우
2. https://github.com/Park747/Likelion-Assignment/tree/master/session04_HW
3.
![Everytime_clone_img](https://user-images.githubusercontent.com/101241978/160273901-f9c3c6c6-3e6a-407f-958d-966477866d60.png)

**Comment by notaonce** [comment]
1. 한성수
2. https://github.com/notaonce/Assignment1.git
3.
![에타클론캡쳐](https://user-images.githubusercontent.com/87408958/160274506-fca07964-1a38-444e-abe5-5b44e6ffa079.png)

**Comment by seoulmango** [comment]
1. 박기만
2. https://github.com/seoulmango/Likelion2022_HW/tree/master/Session04_HW
3.
<img width="1552" alt="everytime_clone_1" src="https://user-images.githubusercontent.com/93420605/160276183-5ece0e91-c267-46c5-b7c5-18a3a3c562ae.png">

<img width="1552" alt="everytime_clone_2" src="https://user-images.githubusercontent.com/93420605/160276189-2b86246e-cad3-4077-bf6e-2cf27b428e7d.png">

<img width="1552" alt="everytime_clone_3" src="https://user-images.githubusercontent.com/93420605/160276190-8262cfd1-d554-4b45-97b5-bab721698ef5.png">

**Comment by CryingDitto** [comment]
1. 이지은
2. https://github.com/CryingDitto/NextLionX/tree/master/Session04_HW
3. 
![cut1](https://user-images.githubusercontent.com/101262081/160277402-f5b609a5-f60d-4060-a861-4e64ab69e5b3.png)
![cut2](https://user-images.githubusercontent.com/101262081/160277408-41c9553a-4a7e-4671-8ec2-2552ee5c465f.png)

**Comment by toyo30** [comment]
1. 이름
2. https://github.com/toyo30/next-like-lion/tree/main/Session04_HW
3.
![Pasted Graphic 14](https://user-images.githubusercontent.com/55613446/160277904-cbc5c103-73e5-439b-ae5c-29446489a825.png)

https://user-images.githubusercontent.com/55613446/160277913-b0fd372c-7fb9-4fda-9fb5-79e41fb2fee7.mp4

**Comment by sde0116** [comment]
1. 서다은
2. https://github.com/sde0116/NextLikeLion/tree/master/Session4_HW
3. 
![image](https://user-images.githubusercontent.com/101265923/160281633-3f03b836-9491-45c5-bfc6-34a24a87d9d9.png)

**Comment by ssoy0514** [comment]
1. 이소희
2. https://github.com/ssoy0514/NextxLikelion-HW/tree/master/Session4-HW
3.
![image](https://user-images.githubusercontent.com/101264437/160285523-82c6b513-9c2f-4182-93ef-e60571dca79a.png)

**Comment by Canada-Joose** [comment]
1. 주장규
2. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session4_HW
3. 에브리타임 클론 코딩 캡쳐 화면

<img width="463" alt="에브리타임_과제_스크린샷" src="https://user-images.githubusercontent.com/100463676/160288503-a057bfb3-41c6-46c2-8d6f-a4ae9e43df3f.png">

**Comment by sonsoowon** [comment]
1. 손수원
2. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session4_HW
3. 
![capture1](https://user-images.githubusercontent.com/55790232/160290323-56c6d658-7a52-462a-8f38-3aeaef78e89f.png)
![capture2](https://user-images.githubusercontent.com/55790232/160290327-702e5f0a-5050-426c-85a8-408dfc9548f5.png)

**Comment by Serinnnnn** [comment]
1. 홍세린
2. https://github.com/Serinnnnn/LIKELION-HW-/tree/main/Session4/Session4_HW
3.
<img width="339" alt="스크린샷 2022-03-27 오후 10 38 45" src="https://user-images.githubusercontent.com/101257662/160290449-b2846630-4be8-4b2d-ba01-22ba343bab2e.png">

**Comment by alswlalswl1013** [comment]
1. 김민지
2. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session4_HW
3.
<img width="220" alt="에브리타임과제캡처" src="https://user-images.githubusercontent.com/101307543/160290591-4f51a103-d022-45c9-8f3f-a0e4e952be6b.PNG">

**Comment by fortepiano13** [comment]
1. 양휘민
2. https://github.com/fortepiano13/HW/tree/main/Session4_HW
3.
<img width="501" alt="화면 캡처 2022-03-28 005207" src="https://user-images.githubusercontent.com/101318912/160292058-a991c851-3b32-4be1-b960-37c61502f5a7.png">
<img width="491" alt="화면 캡처 2022-03-28 005310" src="https://user-images.githubusercontent.com/101318912/160292063-057b84d2-5f0f-4e3a-b9aa-89e8440d27d4.png">

**Comment by Pelixhoon** [comment]
1. 송명훈
2. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session04_HW
3.
<img width="381" alt="스크린샷 2022-03-28 오전 2 30 23" src="https://user-images.githubusercontent.com/101280374/160293578-7a8d6f2a-44fc-465a-ad5e-48fbae06c542.png">
<img width="386" alt="스크린샷 2022-03-28 오전 2 31 14" src="https://user-images.githubusercontent.com/101280374/160293588-e6506263-1a89-4215-9a34-0958072f1be2.png">

**Comment by y0oo0n** [comment]
1. 윤정윤
2. https://github.com/y0oo0n/Homeworks/tree/main/Session4_HW
3.
![everytime_clone](https://user-images.githubusercontent.com/101259370/160295565-7a70e328-def6-41f7-9732-b4b03795f938.JPG)

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session04_HW
3.
![everytime_copycoding](https://user-images.githubusercontent.com/99478871/160309538-97ec78f0-5bec-4136-9add-335effd96ccb.png)

**Comment by Moi1oM** [comment]
1. 전성운
2.  https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session4_HW
3.  
![image](https://user-images.githubusercontent.com/101260709/160310454-3a68ed42-333a-4b1f-a9f9-0e461bb8e70d.png)

**Comment by extrajunwan** [comment]
1. 박준완
2. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session4_HW
3.
<img width="439" alt="스크린샷 2022-03-28 오전 10 29 16" src="https://user-images.githubusercontent.com/101266326/160311541-765d2058-961e-4d5c-b909-a9dc2b4c2516.png">

**Comment by nymvmt** [comment]
> 
1. 김나영
2. https://github.com/nymvmt/Next_LikeLion_2022/tree/master/Session4_HW
3.
<img width="612" alt="ScreenShot  Everytime_1" src="https://user-images.githubusercontent.com/99931269/160331503-a99344c1-8f67-4ce7-89f8-299f030f4330.png">
<img width="609" alt="ScreenShot  Everytime_2" src="https://user-images.githubusercontent.com/99931269/160331514-2a03f41c-34f5-4501-bb23-342409bb35b3.png">
<img width="617" alt="ScreenShot  Everytime_3" src="https://user-images.githubusercontent.com/99931269/160331518-b813b1aa-46da-4d7e-82fb-3f3fb6e221fe.png">

**Comment by innerstella** [comment]
1. 차수지
2. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session4_HW
3.
<img width="221" alt="everytime" src="https://user-images.githubusercontent.com/77491430/160340794-4bc966c3-c426-4077-a63a-7613c72c39f4.png">

**Comment by HaYoonsoo** [comment]
1. 하윤수

2. https://github.com/HaYoonsoo/likelion/tree/master/Session4_HW
3.
![스크린샷 2022-03-28 오후 3 38 45](https://user-images.githubusercontent.com/101256025/160341001-05aef685-a0e4-4798-adf2-5ba0e695c140.png)

**Comment by jisoolee0929** [comment]
1. 이지수
2. https://github.com/jisoolee0929/NEXTLION/tree/master/Session4_HW(크롤링)
https://github.com/jisoolee0929/NEXTLION/tree/master/Session4-1_HW(에타)
3
![에타](https://user-images.githubusercontent.com/62417326/160348732-3b88c1d4-cdef-4ae7-b91a-7245ca0d0386.PNG)
.

**Comment by willbeagangsta** [comment]
1. 김하경
2. https://github.com/willbeagangsta/Next_Lion_Gang/tree/master/Homeworks/Session4_HW
3. 
![화면캡쳐](https://user-images.githubusercontent.com/101272176/160354192-5713b816-2ec5-4aae-a00d-c927ebd7f592.PNG)

**Comment by kchaehyeon01** [comment]
1. 김채현
2. https://github.com/kchaehyeon01/NEXTLikeLion2022.git
3. 
![image](https://user-images.githubusercontent.com/80916105/160358292-04ac8903-ad45-4369-94cd-68c7c4580377.png)

**Comment by eauchan** [comment]
1. 이의찬
2. https://github.com/eauchan/Next_LikeLion/tree/main/Session4_HW
3.
<img width="232" alt="에브리타임" src="https://user-images.githubusercontent.com/91827518/160359001-d60fcbd6-14a0-48ab-9529-abeac3f2d34c.PNG">

**Comment by ziw00** [comment]
1. 정지우
2. https://github.com/ziw00/session04_hw.git

**Comment by JHLvJz** [comment]
1. 문지후
2. https://github.com/JHLvJz/NxL2022/tree/master/Session4_HW
3.
<img width="436" alt="에브리타임클론코딩" src="https://user-images.githubusercontent.com/101316991/160364842-10a05454-0510-48ab-89b3-5dc6d6d64992.png">

**Comment by dizolion** [comment]
1. 박소정
2. https://github.com/dizolion/skycolor10/tree/master/Session4
3.
![그룹 1](https://user-images.githubusercontent.com/101280974/160366100-90cc35bc-401a-4fd0-9c56-f44f44c4e0a7.png)

**Comment by 99rbbt** [comment]
1.신재현
2.https://github.com/99rbbt/Nextlion2022/tree/master/Session4_HW
3
![화면 캡처 2022-03-28 182953](https://user-images.githubusercontent.com/101272544/160369853-3814dc24-941a-4db8-b979-18ccccb73da7.jpg)
.

**Comment by onelee812** [comment]
1. 이예원
2. https://github.com/onelee812/LikeLion22/tree/main/Session4_HW
3.
<img width="219" alt="everytime_clone" src="https://user-images.githubusercontent.com/98938138/160370418-64a3b411-428f-4e20-a04e-d9e13a92e77b.png">

**Comment by baby-crows** [comment]
1. 이영서
2. https://github.com/monator16/Likelion.practice/tree/master/Session4_HW
3.
![에타클론코딩캡처샷](https://user-images.githubusercontent.com/101310701/160370959-43f04b98-0018-4621-b2f3-4c4d5d46587b.PNG)

**Comment by sophiahyj** [comment]
1. 한예진
2. https://github.com/sophiahyj/likelionHW/tree/master/Session4_HW
3.
![everytimecapture](https://user-images.githubusercontent.com/101271670/160373394-c11e2280-10aa-413d-aa48-451b19c97af4.PNG)

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session4_HW
3.
<img width="1440" alt="에브리타임" src="https://user-images.githubusercontent.com/89579178/160897390-bbf65b1e-2cf8-4d58-ac72-6740aaef2aff.png">

**Comment by reason-jinny** [comment]
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session4_HW
3. 
<img width="393" alt="에타클론" src="https://user-images.githubusercontent.com/101304885/166096309-cf452534-28da-4556-bea8-3d94bbd18055.png">
