### ISSUE TITLE
[NEXT 10th Assignment] Session 5 - 장고 기초

### ISSUE THREAD

**Issue by kulikelion** [NEXT-LIKELION/2022-NEXT-Assignment#7]
### [과제]
- 단어수 세는 기능을 추가해서 글자수 세기 프로젝트 만들기
- count.html, result.html 꾸미기
- (선택) 목요일 세션에 입고 올 교복 챙기기🙃

### [과제 업로드 예시]
1. 이름
2. count, result 페이지 캡처화면(페이지 이동이 보이는 .gif 형태 권장)
3. 과제 깃헙 링크
(.gitignore에 올릴 필요 없는 파일들을 명시하고 project 전체 폴더 혹은 project 전체 폴더를 담고 있는 session5 과제 폴더를 각자 깃헙에 올려주세요!)

**Comment by extrajunwan** [comment]
1. 박준완
2.
![장고 세션 숙제](https://user-images.githubusercontent.com/101266326/160570189-96a195d6-2b64-4c25-b0bb-a5c59ed20c7e.gif)
3. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session5_HW

**Comment by seoulmango** [comment]
1. 박기만

2.
![ezgif-2-8d43127598](https://user-images.githubusercontent.com/93420605/160583075-35065595-7ad8-4cb4-87c9-878d4998aece.gif)

3.  https://github.com/seoulmango/Likelion2022_HW/tree/master/Session05_HW

**Comment by Park747** [comment]
1. 박견우
2.
![멋사전용_글자수_세기_프로그램_-_Chrome_2022-03-29_19-55-46_AdobeCreativeCloudExpress (1)](https://user-images.githubusercontent.com/101241978/160599041-0d29f76f-22cf-441a-abb0-dcf9128031fa.gif)
3. https://github.com/Park747/Likelion-Assignment/tree/master/session05_HW

**Comment by 99rbbt** [comment]
1.신재현
2. 
![homework_AdobeCreativeCloudExpress (1)](https://user-images.githubusercontent.com/101272544/160626711-f49fe0af-ee0c-44de-8015-5ae79ca08ce4.gif)

3.https://github.com/99rbbt/Nextlion2022/tree/master/Session5_HW

**Comment by CryingDitto** [comment]
1. 이지은
2. 
![Animation (2)](https://user-images.githubusercontent.com/101262081/160745845-2b9079c8-3e02-4c14-a2f6-e12f64bf5f9f.gif)

3. https://github.com/CryingDitto/NextLionX/tree/master/Session05_HW

**Comment by eauchan** [comment]
1.이의찬
2.
![Animation](https://user-images.githubusercontent.com/91827518/160785582-ca63f6c7-87a7-4c5a-b497-da79b4fc8f9c.gif)
3.https://github.com/eauchan/Next_LikeLion/tree/main/Session5_HW

**Comment by sde0116** [comment]
1. 서다은
2.
![Session5_HW](https://user-images.githubusercontent.com/101265923/160819934-89a2f168-1ad5-42c4-91fc-bdab3897d66b.gif)
3. https://github.com/sde0116/NextLikeLion/tree/master/Session5_HW

**Comment by ghost** [comment]
1. 김지욱
2. 
![log](https://user-images.githubusercontent.com/99459331/160826767-189c6630-730a-4fc6-bfa0-9094bbda17bd.gif)
3. https://github.com/ziweek/likelion/tree/master/Assignments/Session5_HW

**Comment by Canada-Joose** [comment]
1. 주장규
2.
![JJK_HW](https://user-images.githubusercontent.com/100463676/160838979-6ab3a6ec-fa32-48a7-8aa2-70ef20985837.gif)
3. https://github.com/Canada-Joose/Likelion_HW/tree/master/Session5_HW

**Comment by toyo30** [comment]
1. 백민기
2.
![Mar-30-2022 22-37-31](https://user-images.githubusercontent.com/55613446/160848025-e7e7edde-5ccd-4992-b122-4b71f50760e6.gif)
3. 과제 깃헙 링크
https://github.com/toyo30/next-like-lion/tree/main/Session05_HW/CountProject

**Comment by notaonce** [comment]
1. 한성수
2.
![글자수세기](https://user-images.githubusercontent.com/87408958/160849371-d5badb66-d520-40d2-b26b-9b32b3ffeba1.gif)
3. https://github.com/notaonce/Assignment1.git

**Comment by JHLvJz** [comment]
1. 문지후
2. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/101316991/160851701-ac325c19-88d8-4f2a-ac58-d31c4de2b1f0.gif)
3. https://github.com/JHLvJz/NxL2022/tree/master/Session5_HW

**Comment by Moi1oM** [comment]
1. 전성운
2.
![제출gif](https://user-images.githubusercontent.com/101260709/160857737-b057f4df-ddf3-4d89-82ef-1ca75fd64ef7.gif)
 3. https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session5_HW

**Comment by Serinnnnn** [comment]
1. 홍세린
2.

https://user-images.githubusercontent.com/101257662/160874031-d9ad12d2-443f-440d-8cca-8f0faca15716.mov

3.https://github.com/Serinnnnn/LIKELION-HW-/tree/main/Session5/Session5_HW

**Comment by sonsoowon** [comment]
1. 손수원
2. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/55790232/160885095-fa16333f-9ed0-4fd2-81f7-c41ecfbaa651.gif)
3. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session5_HW

**Comment by Pelixhoon** [comment]
1. 송명훈
2. ![송명훈-글자수세기](https://user-images.githubusercontent.com/101280374/160887317-aa199d09-99ef-4f35-bce7-abad4998d24d.gif)
3. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session05_HW

**Comment by HaYoonsoo** [comment]
1. 하윤수
2. ![video](https://user-images.githubusercontent.com/101256025/160906621-f7232270-cd5b-45c3-a22e-6cac409b95a1.mp4)
3. https://github.com/HaYoonsoo/likelion/tree/master/Session5_HW

**Comment by ssoy0514** [comment]
1. 이소희
2.
![Animation](https://user-images.githubusercontent.com/101264437/160974396-7030e206-9fa7-4b88-90ec-4e2629c8b8a1.gif)
3.https://github.com/ssoy0514/NextxLikelion-HW/tree/master/Session5_HW

**Comment by alswlalswl1013** [comment]
1. 김민지
2.

https://user-images.githubusercontent.com/101307543/160974518-a565bbe7-758b-494f-83df-155215f50a4c.mp4

3. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session5_HW

**Comment by ssoy0514** [comment]
1. 이소희
2.
![submit](https://user-images.githubusercontent.com/101264437/160976258-95fcd921-d6e8-4db6-afa0-17fb5cce21ca.gif)
3. https://github.com/ssoy0514/NextxLikelion-HW/tree/master/Session5_HW

**Comment by innerstella** [comment]
1. 차수지
2.
![hw5](https://user-images.githubusercontent.com/77491430/160985216-9956da86-a636-4386-8109-14c2bb4322d6.gif)
3. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session5_HW

**Comment by nymvmt** [comment]
1.김나영
2.
![CountProject](https://user-images.githubusercontent.com/99931269/160993204-9162a33f-b145-45e0-8dde-9ceefe6759e0.gif)
3.https://github.com/nymvmt/Next_LikeLion_2022/tree/master/Session5_HW

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2.
![session5](https://user-images.githubusercontent.com/99478871/161012236-0bb90138-b678-4ca8-8c16-a4cd6cb3a1c6.gif)



3. https://github.com/HyeyoungEum/2022NEXTLikeLion/tree/master/Session5_2/ex1

**Comment by jisoolee0929** [comment]
1. 이지수
2.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/62417326/161010646-aace35d9-9de9-408c-aaa6-6669ddc24a78.gif)
3. https://github.com/jisoolee0929/NEXTLION/tree/master/Session5_HW

**Comment by y0oo0n** [comment]
1. 윤정윤
2.

![멋사 글자수](https://user-images.githubusercontent.com/101259370/161012356-198598fd-b626-4e32-afdd-1dda40152252.gif)


3.  https://github.com/y0oo0n/Homeworks/tree/main/Session5_HW

**Comment by sophiahyj** [comment]
1. 한예진
2.
![Animation](https://user-images.githubusercontent.com/101271670/161020873-b6bd01d6-a939-47de-a7d5-d568b881a954.gif)
3. https://github.com/sophiahyj/likelionHW/tree/master/Session5_HW

**Comment by kchaehyeon01** [comment]
1. 김채현
2. 
3. https://github.com/kchaehyeon01/NEXTLikeLion2022/tree/master/Session5_HW

**Comment by fortepiano13** [comment]
1. 양휘민
2.
<img width="220" alt="화면 캡처 2022-03-31 181928" src="https://user-images.githubusercontent.com/101318912/161023076-d226af12-dffc-4a80-a1a4-25400e642352.png">
<img width="461" alt="화면 캡처 2022-03-31 182130" src="https://user-images.githubusercontent.com/101318912/161023087-34e2f667-19b1-44a2-8e70-d51d4c25e72e.png">
3.  https://github.com/fortepiano13/HW/tree/main/Session5_HW

**Comment by onelee812** [comment]
1. 이예원
2. 

![글자수세기](https://user-images.githubusercontent.com/98938138/162996817-fe3799dc-f3ae-477f-b6e1-2b8fe42ff8c9.gif)



3. https://github.com/onelee812/LikeLion22/tree/main/Session5_HW

**Comment by ziw00** [comment]
1. 정지우
2.
https://user-images.githubusercontent.com/101320633/161031039-3cb6b0f3-2fdb-4a23-8b45-547b2665879b.mov

**Comment by willbeagangsta** [comment]
1. 김하경
2. https://github.com/willbeagangsta/Next_Lion_Gang

**Comment by rfdseoul** [comment]
1. 전민철
2. https://github.com/rfdseoul/firstsession/tree/master/session5_HW
3.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/89579178/162416188-6306eace-0dbe-4db0-bda4-4eca98174ea2.gif)

**Comment by baby-crows** [comment]
1.이영서
2. https://github.com/monator16/Likelion.practice/tree/main/Session05_HW
3.

https://user-images.githubusercontent.com/101310701/165936913-910f902d-3d56-4237-8ed6-9ddf5165bc66.mp4

**Comment by dizolion** [comment]
1. 박소정
2.https://github.com/dizolion/skycolor10/tree/master/session5HW
3.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/101280974/166072650-2d7ed8f4-5c74-4363-8f80-8499c881ca77.gif)

**Comment by reason-jinny** [comment]
1. 이유진
2. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session5_HW
3.

https://user-images.githubusercontent.com/101304885/166096372-955fca72-a796-4a9c-80a7-0fd86d1726e4.mov

**Comment by Minyongggg** [comment]
댓글
