### ISSUE TITLE
[NEXT 10th Assignment] Session 6 - DB + 장고 CR

### ISSUE THREAD

**Issue by Minyongggg** [NEXT-LIKELION/2022-NEXT-Assignment#8]
### 4/4 세션 전까지 댓글로 과제 인증해주세요!

[과제1]
- 블로그 게시글에 “카테고리＂ 추가 : 취미(hobby), 음식(food), 프로그래밍(programming)
- List 페이지에는 카테고리 별 게시판으로 이동하는 링크와 각 카테고리의 게시글 갯수 보여주기
- 각 카테고리 별 게시판에는 해당 카테고리의 게시글 목록만 보여주기
- Detail 페이지에서는 글 제목, 내용, 글 작성시각 보여주기
- CSS도 예쁘게 꾸며서 적용해보기

[과제2]
- 원하는 대상(장소, 집단, 서비스 등)을 자유롭게 하나 정하고 대상의 구성요소를 생각하며
DB schema diagram 그리기
- 단, 테이블 개수 5개 이상!
- 그리는 툴은 무관 ( 파워포인트, dbdiagram.io, 손 그림 등 )
- 인터넷에서 예시 참고하여 따라 그려도 무관

[과제 업로드 예시]
- 이름
- 블로그 각 페이지에서의 기능(기능 작동이 보이는 .gif 형태 권장)
- django 프로젝트 깃헙 링크
- DB shema diagram 이미지

**Comment by eauchan** [comment]
1. 이의찬
2. 
![Animation](https://user-images.githubusercontent.com/91827518/161473947-bb5d6920-2c90-414d-8961-1e6ad5f0bcb2.gif)

3. https://github.com/eauchan/Next_LikeLion/tree/main/Session6
4.
![데이터 스키마](https://user-images.githubusercontent.com/91827518/161473927-5fe5e54a-e19e-4810-966d-1c6321e2c1ba.png)

**Comment by CryingDitto** [comment]
1. 이지은
2.
![Animation_django2](https://user-images.githubusercontent.com/101262081/161476621-168c34c4-93a8-481c-a48d-b46b05608ab8.gif)
3. https://github.com/CryingDitto/NextLionX/tree/master/Session06_HW
4.
![db_diagram drawio](https://user-images.githubusercontent.com/101262081/161476836-aa5050b2-1afb-43aa-bec3-fd72511677df.png)

**Comment by toyo30** [comment]
1. 백민기
2.
![Apr-04-2022 00-39-28](https://user-images.githubusercontent.com/55613446/161477689-e7a47b4b-d001-454a-8488-5924d626705c.gif)
3. django 프로젝트 깃헙 링크
https://github.com/toyo30/next-like-lion/tree/main/Session06_HW/blogProject
4. DB shema diagram 이미지
![Pasted Graphic](https://user-images.githubusercontent.com/55613446/161477975-e2afeb6f-f488-48a7-9d43-6a242daa71ea.jpg)

**Comment by HaYoonsoo** [comment]
1. 하윤수
2.

https://user-images.githubusercontent.com/101256025/161478108-8d3a6a4a-7fdb-49d5-a35e-0dc0f736cb26.mp4

3. https://github.com/HaYoonsoo/likelion/tree/master/Session6_HW/blogProject
4. 
![스크린샷 2022-04-04 오후 2 05 13](https://user-images.githubusercontent.com/101256025/161478133-14bdd263-c642-49b4-8c21-2c4f3fe31897.png)

**Comment by innerstella** [comment]
1. 차수지
2. 
![blog](https://user-images.githubusercontent.com/77491430/161478407-54b39f8e-bd62-44aa-a570-e6cecc439aa5.gif)

3. https://github.com/innerstella/NEXT-X-LION-10/tree/master/Session6_HW
4.
<img width="283" alt="diagram" src="https://user-images.githubusercontent.com/77491430/161478401-55b0f661-1c5e-4464-8b2e-1803ba6c4931.png">

**Comment by jisoolee0929** [comment]
1. 이지수
2. 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/62417326/161481743-d153bf86-e7d1-4616-9caf-a12504f81beb.gif)
3. https://github.com/jisoolee0929/NEXTLION/tree/master/Session6
4.
![데이터스키마](https://user-images.githubusercontent.com/62417326/161481809-a53d2b3c-c129-4548-bf62-e8c9a74bba4c.PNG)

**Comment by seoulmango** [comment]
1. 박기만
2.

https://user-images.githubusercontent.com/93420605/161486281-0d8666b4-eb64-4124-a6cb-194403eae4de.mov


3.  https://github.com/seoulmango/Likelion2022_HW/tree/master/Session06_HW
4.
<img width="798" alt="Screen Shot 2022-04-04 at 3 04 34 PM" src="https://user-images.githubusercontent.com/93420605/161485483-5b6d6335-1129-4954-8da6-6921bd7c8a15.png">

**Comment by sde0116** [comment]
1. 서다은
2.
![Session6_HW](https://user-images.githubusercontent.com/101265923/161486981-20266ef4-dd63-462d-bd69-eb40730c52a6.gif)
3. https://github.com/sde0116/NextLikeLion/tree/master/Session6_HW
4. 
![DB schema diagram](https://user-images.githubusercontent.com/101265923/161487308-5520aa2e-fb6f-4e16-a895-e47d0093d5ca.png)

**Comment by Moi1oM** [comment]
1. 전성운
2.

https://user-images.githubusercontent.com/101260709/161490672-e147015d-68da-4dd1-a2df-07e97d7f357d.mp4


3.
https://github.com/Moi1oM/Next_likelion_HW/tree/master/Session6_HW
4.
![DB](https://user-images.githubusercontent.com/101260709/161490193-ea89c72e-e76d-4771-8fc6-22ef7fffb93d.jpg)

**Comment by Serinnnnn** [comment]
1.홍세린
2

https://user-images.githubusercontent.com/101257662/161494514-4e3f7b6f-4872-487b-ab1c-d6f2f7a70860.mov

.

3
![db schema](https://user-images.githubusercontent.com/101257662/161494616-9f7bfb2f-cdf6-4617-956f-ab397d975043.jpg)
.

**Comment by ghost** [comment]
1. 김지욱
2.
![log](https://user-images.githubusercontent.com/99459331/161496818-873a8712-8095-4e82-9c59-c1132f502375.gif)
3. https://github.com/ziweek/likelion/tree/master/Assignments/Session6_HW
4.
<img width="998" alt="DBgram" src="https://user-images.githubusercontent.com/99459331/161496902-a5890ac9-ac7f-4616-84b7-785a392749e5.png">

**Comment by ssoy0514** [comment]
1. 이소희
2.
![session7bloghw](https://user-images.githubusercontent.com/101264437/161501489-39dafcdf-037c-44b1-8a42-188ba66edbfa.gif)
3. https://github.com/ssoy0514/NextxLikelion-HW/tree/master/Session6_HW
4. 
![사본 -KakaoTalk_20220404_171143235](https://user-images.githubusercontent.com/101264437/161502257-0017fb60-5160-43dd-8bd4-a3537e9bcd8f.jpg)

**Comment by willbeagangsta** [comment]
1. 김하경
2. 제대로 작동을 안합니다,,, 추후에 발전시켜보겠습니다 ㅜㅜ
![블로그화면](https://user-images.githubusercontent.com/101272176/161501748-b4e40644-319f-49cd-8930-091f5eb989a6.PNG)
3. https://github.com/willbeagangsta/Next_Lion_Gang/tree/master/Homeworks/Session6_HW
4. 
[schema.pdf](https://github.com/NEXT-LIKELION/2022-NEXT-Assignment/files/8407898/schema.pdf)

**Comment by 99rbbt** [comment]
1. 신재현
2

https://user-images.githubusercontent.com/101272544/161502435-cc39b087-a8a7-4caa-822f-62ca134b0ced.mp4

.
3.https://github.com/99rbbt/Nextlion2022/tree/master/Session6_HW
4
![화면 캡처 2022-04-04 165837](https://user-images.githubusercontent.com/101272544/161502553-96a33dc3-1b53-4368-a33d-1db63cfec901.jpg)
.

**Comment by extrajunwan** [comment]
1. 박준완
2. 작성한 글을 submit 하고 리스트 화면으로 넘어가야 하는데 에러가 뜹니다... 구글링하고 아무리 찾아봐도 해결이 안돼서 나중에 운영진 분들한테 여쭤보고 도움 받고 최종 수정해서 다음번 과제 때 같이 제출하겠습니다 ㅠㅠ 죄송합니다!
3. https://github.com/extrajunwan/NEXTLikeLion10th/tree/master/Session6_HW
4. 
![DB scheme diagram](https://user-images.githubusercontent.com/101266326/161503142-8a1fca5b-ec02-4501-841d-0dea7941781b.jpeg)

**Comment by Pelixhoon** [comment]
1. 송명훈
2. 
![Session06_과제제출용](https://user-images.githubusercontent.com/101280374/161503436-40232200-eeaa-492f-b048-fb57d3e10dff.gif)
3. https://github.com/Pelixhoon/NEXTxLikelion/tree/master/Session06_HW
4. 
![Schema Diagram 송명훈](https://user-images.githubusercontent.com/101280374/161503681-83f86ff8-da8a-4f02-a3dc-002667c40525.jpg)

**Comment by Canada-Joose** [comment]
1. 주장규
2. 
![화면 기록 2022-04-04 오후 5 17 22](https://user-images.githubusercontent.com/100463676/161503829-6fee1d15-6ed4-4074-85ed-54c656268313.gif)
3.  https://github.com/Canada-Joose/Likelion_HW
4.
![DB_schema](https://user-images.githubusercontent.com/100463676/161503926-9882803f-5d19-4437-8c23-4b2074a5cf47.png)

**Comment by dizolion** [comment]
1. 박소정
2. 자꾸 오류가 떠서 이번 세션 끝나고 다시 만들어보겠습니다 .. 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/101280974/161504590-5b3110e1-1348-4961-80c7-ca500160cae0.gif)

3. 
![맞춤형 크기 – 1](https://user-images.githubusercontent.com/101280974/161500917-806e62d7-761e-4bd9-a3db-96d45eec2244.png)

**Comment by Park747** [comment]
1.박견우
2. 
![My_Blog_-_Chrome_2022-04-04_17-35-23_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/101241978/161507415-4239fea9-c0f5-4b1b-956e-06142e6241ef.gif)
3.
![KakaoTalk_20220404_171646208_01](https://user-images.githubusercontent.com/101241978/161507152-133cde03-c903-4c62-add1-c9bb4f5bf7f7.jpg)
4. https://github.com/Park747/Likelion-Assignment/tree/master/session06_HW

**Comment by sonsoowon** [comment]
1. 손수원
2. 
![새_글_작성_-_Chrome_2022-04-04_17-35-02_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/55790232/161507043-6bcd802d-d1c1-4c14-815f-c9345afca1c7.gif)
3. https://github.com/sonsoowon/Nextlion_HW/tree/master/Session6_HW
4. 
![1](https://user-images.githubusercontent.com/55790232/161507479-c90d8a13-159c-4d41-8960-8e65915425b4.png)

**Comment by notaonce** [comment]
1. 한성수
2. 
![블로그](https://user-images.githubusercontent.com/87408958/161508154-e0a5f160-0351-4b0f-92e0-a9b78723d977.gif)


3. https://github.com/notaonce/Assignment1.git

4. <img width="570" alt="Screen Shot 2022-04-04 at 5 45 45 PM" src="https://user-images.githubusercontent.com/87408958/161508235-3c02f580-bbd9-43ba-8dd7-b3ec0788dbca.png">

**Comment by alswlalswl1013** [comment]
1. 김민지
2.
![블로그_글_작성_페이지_-_Chrome_2022-04-04_오후_3_10_14_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/101307543/161509790-4b217000-7084-4b68-914d-f9a88e16fba3.gif)
3. https://github.com/alswlalswl1013/LIKELION2022/tree/master/Session6_HW
4. 
![KakaoTalk_20220404_145144485](https://user-images.githubusercontent.com/101307543/161510042-14ae9803-a1f9-4d91-9744-506b2bcffcb2.jpg)

**Comment by kchaehyeon01** [comment]
1. 김채현
2. 실패...기본적인것들도 실패해서 장고부터 다시 복습 후 해보겠습니다..!
![image](https://user-images.githubusercontent.com/80916105/161510831-cec2085b-7858-49a3-95bd-8a0f4c34253a.png)

3. https://github.com/kchaehyeon01/NEXTLikeLion2022.git
4. ![DB schema diagram](https://user-images.githubusercontent.com/80916105/161510709-7c687ebf-5d16-41f0-8707-88ddfd32c8a5.png)

**Comment by fortepiano13** [comment]
1. 양휘민
2. operationalerror: no such column 뜨면서 안 돌아가네요... 나중에 지각으로라도 내겠습니다
3. https://github.com/fortepiano13/HW/tree/main/session6/blogProject/blogApp
4.
![KakaoTalk_20220404_182346254](https://user-images.githubusercontent.com/101318912/161514780-15867135-fe98-4588-bdcf-e9507760386d.jpg)

**Comment by nymvmt** [comment]
1. 김나영
2. 

https://user-images.githubusercontent.com/99931269/161516420-f129dc1d-7972-4bbe-93fb-822c9dc0e61e.mov


3. https://github.com/nymvmt/Next_LikeLion_2022/tree/master/Session6_django%202/Session6_HW/HW1_blogProject
4.
![PNG  DB Schema diagram](https://user-images.githubusercontent.com/99931269/161516793-a977590a-7c7c-406e-8b83-059915e7e2cc.png)

**Comment by y0oo0n** [comment]
1. 윤정윤
2.
https://user-images.githubusercontent.com/101259370/162111075-a8f0d18e-b0d6-4943-aa44-fa31ca7b0139.mp4

3. https://github.com/y0oo0n/Homeworks/tree/main/Session6_HW
4.
![DB schema diagram_윤정윤](https://user-images.githubusercontent.com/101259370/161520291-56731b67-6eff-4354-9262-174c3c03d459.png)
 
CSS는 끝까지 못했지만 .. 제출합니당 하하핳 🌺

**Comment by sophiahyj** [comment]
1. 한예진
2. 
![blogprojectgif](https://user-images.githubusercontent.com/101271670/161522313-84ff36f0-7604-4e73-b8ca-7a325cad1399.gif)
기능구현에 시간이 오래걸려서 CSS에 신경을 못썼습니다ㅜㅜ추후에 보완하겠습니다!
3. https://github.com/sophiahyj/likelionHW/tree/master/Session6_HW
4.
![db](https://user-images.githubusercontent.com/101271670/161521623-7ab4c499-7be8-49d2-bc53-fcc00c0f95b0.jpg)

**Comment by onelee812** [comment]
1. 이예원
2.

https://user-images.githubusercontent.com/98938138/163075638-0697dd79-e79c-40af-8c7c-6d253c913fc4.mov

3. https://github.com/onelee812/LikeLion22/tree/main/Session6_HW
4. 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/98938138/163075772-aaa85ae6-ee86-4e3d-be4a-8275f33837be.png">

**Comment by baby-crows** [comment]
1, 이영서
2.


https://user-images.githubusercontent.com/101310701/166078223-95fe653a-154c-48a6-9c49-0119011da55c.mp4

3.
https://github.com/monator16/Likelion.practice/tree/main/session6

4.
![image](https://user-images.githubusercontent.com/101310701/166078404-6718aebe-1bd8-447f-aac6-36a27ca0db12.png)

**Comment by rfdseoul** [comment]
1. 전민철
2. 
![과제 제출본](https://user-images.githubusercontent.com/89579178/166092388-f61c3411-df14-406a-9c9c-91c86eaf6d62.gif)
3. https://github.com/rfdseoul/firstsession/tree/master/session6_HW
4.
<img width="1035" alt="과제 제출본" src="https://user-images.githubusercontent.com/89579178/166092402-f683bd96-f691-4262-800b-c94e40c30c73.png">

**Comment by reason-jinny** [comment]
1. 이유진
2.

https://user-images.githubusercontent.com/101304885/166096433-e5cc46b0-88e7-4f31-aefb-f52a47bcc9bf.mov

3. https://github.com/reason-jinny/NEXTLikeLion/tree/master/Session6_HW
4. 
![이미지-2](https://user-images.githubusercontent.com/101304885/166096443-209018ef-ab95-4037-8e0c-9d5a9022ec04.jpg)

**Comment by ziw00** [comment]
1. 정지우
2.
<img width="305" alt="스크린샷 2022-04-30 16 47 02" src="https://user-images.githubusercontent.com/101320633/166096874-18441a2d-c755-4a85-a57b-b1730f07bbf3.png">

3. https://github.com/ziw00/session06.git
4.

**Comment by HyeyoungEum** [comment]
1. 엄혜영
2.
<img width="1440" alt="엄혜영" src="https://user-images.githubusercontent.com/99478871/166097166-4ccf0fcd-57ad-484d-8c0b-a9718805687e.png">

3. https://github.com/HyeyoungEum/2022NEXTLikeLion2/tree/master/Session6_4

4. https://drive.google.com/file/d/1kAMcdcDBiX5AaWYvEjmxB2vV1aGRDEGb/view?usp=sharing

**Comment by JHLvJz** [comment]
1. 문지후
2. 아직 시험이 안 끝나서... 한 부분까지만 올립니다 ㅠㅠ 끝나자마자 완성해서 올리겠습니다 !
3. https://github.com/JHLvJz/NextxLikelion/tree/master/HW_Session6/Myblog
4. 
![IMG_2329](https://user-images.githubusercontent.com/101316991/166107298-8d5b44ae-57c2-4d5f-8d9b-645c6b034f9d.jpg)
